name: tech_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
# flutter sdk is 3.24.0
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  logger: ^2.2.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  syncfusion_flutter_charts: ^28.1.35
  intl: ^0.18.0


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    lottie: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 26
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#00FFFFFF"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/files/
    - assets/lottie/

  fonts:
    - family: 'Mulish'
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 600
